export const MOTION_PARTS = [
  {
    id: 'metering', number: '01', short: 'AIR + FUEL', name: 'Throttle body + injectors', color: '#3f9a9d',
    summary: 'The accelerator requests torque by admitting more air and matching fuel.',
    detail: 'This modern engine uses a throttle body to meter air and electronic injectors to meter fuel. An older carburetor used fast air through a venturi to draw fuel from calibrated jets; an injected car does not use both systems at once.',
    studyFlow: ['Pedal request', 'Air + fuel metered', 'Charge enters cylinders'],
    internals: ['Air filter and intake duct', 'Throttle housing, butterfly, and actuator', 'Fuel rail and electronic injectors', 'Intake plenum and runners', 'Carburetor venturi and jet as an older alternative'],
  },
  {
    id: 'engine', number: '02', short: 'ENGINE', name: 'Pistons + crankshaft', color: '#e6543f',
    summary: 'Combustion pressure becomes a twisting crankshaft.',
    detail: 'Hot gas pushes the pistons. Connecting rods push off-center on the crank throws, turning straight piston force into engine torque. Several cylinders overlap their power strokes to keep the shaft turning.',
    studyFlow: ['Gas pressure', 'Piston + connecting rod', 'Crankshaft torque'],
    internals: ['Cylinder head, intake valve, and exhaust valve', 'Spark plug and combustion chamber', 'Piston and sealing rings', 'Connecting rod and crank throw', 'Crankshaft and output flywheel'],
  },
  {
    id: 'coupling', number: '03', short: 'COUPLING', name: 'Flywheel + coupling', color: '#d38d27',
    summary: 'The flywheel smooths pulses; a coupling connects the engine to the gearbox.',
    detail: 'A manual uses friction plates called a clutch. A conventional automatic usually uses a fluid torque converter and lock-up clutch. Either can let engine and wheel speed differ during launch.',
    studyFlow: ['Engine flexplate', 'Fluid coupling + lock-up', 'Gearbox input shaft'],
    internals: ['Flexplate', 'Converter impeller', 'Turbine', 'Stator and one-way clutch', 'Lock-up clutch', 'Transmission input shaft'],
  },
  {
    id: 'gearbox', number: '04', short: 'GEARBOX', name: 'Transmission gears', color: '#76569b',
    summary: 'Gears trade rotational speed for torque.',
    detail: 'A low gear turns the output fewer times per engine revolution, multiplying output torque. A high gear gives less multiplication and more wheel speed. Neutral interrupts the torque path.',
    studyFlow: ['Input rotation', 'Clutch packs + planetary set', 'Selected output ratio'],
    internals: ['Hydraulic clutch packs', 'Sun gear', 'Planet gears and carrier', 'Ring gear', 'Output shaft and bearings'],
  },
  {
    id: 'shaft', number: '05', short: 'DRIVESHAFT', name: 'Driveshaft', color: '#76569b',
    summary: 'A rotating tube carries gearbox torque toward the rear axle.',
    detail: 'This teaching sedan is rear-wheel drive, so it needs a long driveshaft. Front-wheel-drive cars usually package the gearbox and differential together and use shorter half-shafts instead.',
    studyFlow: ['Gearbox flange', 'Tube + joints carry twist', 'Pinion flange'],
    internals: ['Front and rear flanges', 'Universal joints', 'Splined slip joint', 'Hollow torque tube'],
  },
  {
    id: 'differential', number: '06', short: 'DIFFERENTIAL', name: 'Final drive + differential + axles', color: '#65468b',
    summary: 'A final reduction multiplies torque again and sends it left and right.',
    detail: 'The differential drives both axles while allowing the two wheels to rotate at different speeds in a corner. The axle shafts carry that torque to the wheel hubs.',
    studyFlow: ['Pinion input', 'Ring + spider gears', 'Left and right axles'],
    internals: ['Drive pinion', 'Ring gear and final reduction', 'Carrier', 'Spider gears', 'Side gears', 'Axle shafts'],
  },
  {
    id: 'tires', number: '07', short: 'TIRES + ROAD', name: 'Driven tires + contact patches', color: '#28778c',
    summary: 'Wheel torque becomes a force where rubber meets the road.',
    detail: 'The tire pushes backward on the road. Static friction from the road pushes the tire—and the car—forward. If the requested force exceeds available grip, the tire spins instead of making more acceleration.',
    studyFlow: ['Axle torque', 'Wheel + tire deform', 'Road pushes car'],
    internals: ['Splined axle and hub', 'Wheel bearings', 'Rim', 'Tire carcass and reinforcing belts', 'Tread blocks and contact patch'],
  },
]
